In [ ]:
import pandas as pd
df = pd.read_csv('/content/AWCustomers.csv')
df2 = pd.read_csv('/content/AWSales.csv')

In [ ]:
df.head()

CustomerID Title FirstName MiddleName  LastName Suffix  \
0       21173   NaN      Chad          C      Yuan    NaN   
1       13249   NaN      Ryan        NaN     Perry    NaN   
2       29350   NaN     Julia        NaN  Thompson    NaN   
3       13503   NaN  Theodore        NaN     Gomez    NaN   
4       22803   NaN  Marshall          J      Shan    NaN   

             AddressLine1 AddressLine2         City    StateProvinceName  ...  \
0      7090 C. Mount Hood          NaN   Wollongong      New South Wales  ...   
1     3651 Willow Lake Rd          NaN      Shawnee     British Columbia  ...   
2  1774 Tice Valley Blvd.          NaN  West Covina           California  ...   
3         2103 Baldwin Dr          NaN    Liverpool              England  ...   
4         Am Gallberg 234          NaN        Werne  Nordrhein-Westfalen  ...   

         Education      Occupation Gender MaritalStatus HomeOwnerFlag  \
0        Bachelors        Clerical      M             M             1   
1  Partial College        Clerical      M             M             1   
2        Bachelors        Clerical      F             S             0   
3  Partial College  Skilled Manual      M             M             1   
4  Partial College  Skilled Manual      M             S             1   

  NumberCarsOwned NumberChildrenAtHome TotalChildren  YearlyIncome  \
0               3                    0             1         81916   
1               2                    1             2         81076   
2               3                    0             0         86387   
3               2                    1             2         61481   
4               1                    0             0         51804   

   LastUpdated  
0   2017-03-06  
1   2017-03-06  
2   2017-03-06  
3   2017-03-06  
4   2017-03-06  

[5 rows x 24 columns]

In [ ]:
merged_df = pd.merge(df,df2,on='CustomerID',how='inner')
merged_df.to_csv('merged_file.csv')
merged_df.head()

merged_df = merged_df.drop(['CustomerID','FirstName','MiddleName','LastName','AddressLine2','Title','Suffix','PhoneNumber','Education','MaritalStatus','LastUpdated'],axis=1)
merged_df.head()
# merged_df.shape[1]


AddressLine1         City    StateProvinceName CountryRegionName  \
0      7090 C. Mount Hood   Wollongong      New South Wales         Australia   
1     3651 Willow Lake Rd      Shawnee     British Columbia            Canada   
2  1774 Tice Valley Blvd.  West Covina           California     United States   
3         2103 Baldwin Dr    Liverpool              England    United Kingdom   
4         Am Gallberg 234        Werne  Nordrhein-Westfalen           Germany   

  PostalCode   BirthDate      Occupation Gender  HomeOwnerFlag  \
0       2500  1987-11-13        Clerical      M              1   
1    V9B 2C3  1972-07-21        Clerical      M              1   
2      91791  1985-11-09        Clerical      F              0   
3     L4 4HB  1977-10-18  Skilled Manual      M              1   
4      59368  1975-02-05  Skilled Manual      M              1   

   NumberCarsOwned  NumberChildrenAtHome  TotalChildren  YearlyIncome  \
0                3                     0              1         81916   
1                2                     1              2         81076   
2                3                     0              0         86387   
3                2                     1              2         61481   
4                1                     0              0         51804   

   BikeBuyer  AvgMonthSpend  
0          1          50.97  
1          1          53.11  
2          1          54.08  
3          1          56.93  
4          1          55.41

In [ ]:
merged_df.isna().sum()

AddressLine1            0
City                    0
StateProvinceName       0
CountryRegionName       0
PostalCode              0
BirthDate               0
Occupation              0
Gender                  0
HomeOwnerFlag           0
NumberCarsOwned         0
NumberChildrenAtHome    0
TotalChildren           0
YearlyIncome            0
BikeBuyer               0
AvgMonthSpend           0
dtype: int64

In [ ]:
df_normalize = df["MiddleName"]
df_normalize.head()


0      C
1    NaN
2    NaN
3    NaN
4      J
Name: MiddleName, dtype: object

In [ ]:
df_normalize.isna().sum()


7789

In [ ]:
df_normalize.fillna(0)


0        C
1        0
2        0
3        0
4        J
        ..
18356    C
18357    0
18358    0
18359    I
18360    0
Name: MiddleName, Length: 18361, dtype: object

In [ ]:
df_normalize.fillna(method='ffill')

<ipython-input-8-c2dfa3005245>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_normalize.fillna(method='ffill')


0        C
1        C
2        C
3        C
4        J
        ..
18356    C
18357    C
18358    C
18359    I
18360    I
Name: MiddleName, Length: 18361, dtype: object

In [ ]:
df_normalize.fillna(method='bfill')

<ipython-input-9-1208a0a212f6>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df_normalize.fillna(method='bfill')


0          C
1          J
2          J
3          J
4          J
        ... 
18356      C
18357      I
18358      I
18359      I
18360    NaN
Name: MiddleName, Length: 18361, dtype: object

In [ ]:
import numpy as np
# df['TotalChildren'] = df.replace(0,np.nan)
df['TotalChildren'] = df['TotalChildren'].replace(0, np.nan)

In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy='mean')
df['TotalChildren'] = imputer.fit_transform(df[['TotalChildren']])
df['TotalChildren'].isna().sum()


0

In [ ]:
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
df['YearlyIncome'] = scaler.fit_transform(df['YearlyIncome'].values.reshape(-1, 1))
df['YearlyIncome'].head()

0    0.496842
1    0.489453
2    0.536172
3    0.317083
4    0.231958
Name: YearlyIncome, dtype: float64

In [ ]:
from sklearn.preprocessing import OneHotEncoder
encoder  = OneHotEncoder(sparse_output=False)
df['Gender'] = encoder.fit_transform(df[['Gender']])
df.head()
df['Gender'].head()

0    0.0
1    0.0
2    1.0
3    0.0
4    0.0
Name: Gender, dtype: float64

In [ ]:
df_numeric = df[['YearlyIncome','NumberCarsOwned']]
df_numeric.head()

YearlyIncome  NumberCarsOwned
0      0.496842                3
1      0.489453                2
2      0.536172                3
3      0.317083                2
4      0.231958                1

In [ ]:
df_nominal = df[['Gender','MaritalStatus']]
df_nominal.head()

Gender MaritalStatus
0     0.0             M
1     0.0             M
2     1.0             S
3     0.0             M
4     0.0             S

In [ ]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder, KBinsDiscretizer
from sklearn.pipeline import Pipeline

# Discretize and standardize numeric attributes
numeric_transformer = Pipeline([
    ('discretizer', KBinsDiscretizer(n_bins=4, encode='ordinal', strategy='uniform')),
    ('scaler', StandardScaler())
])

# One-hot encode nominal attributes
nominal_transformer = OneHotEncoder(sparse_output=False)



In [ ]:
df_numeric = numeric_transformer.fit_transform(df_numeric)
df_nominal = nominal_transformer.fit_transform(df_nominal)

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


In [ ]:
df_numeric = pd.DataFrame(df_numeric)
df_nominal = pd.DataFrame(df_nominal)

In [ ]:
df_numeric.head()

0         1
0 -0.218318  2.237385
1 -0.218318  0.761523
2  0.811623  2.237385
3 -0.218318  0.761523
4 -1.248258 -0.714339

In [ ]:
df_nominal.head()

0    1    2    3
0  1.0  0.0  1.0  0.0
1  1.0  0.0  1.0  0.0
2  0.0  1.0  0.0  1.0
3  1.0  0.0  1.0  0.0
4  1.0  0.0  0.0  1.0

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity
# Calculate Hamming Distance
nominal_similarity = cosine_similarity(df_nominal)
print("Nominal Similarity (Hamming Distance):\n", nominal_similarity)

numeric_similarity = cosine_similarity(df_numeric)
print("\nNumeric Similarity (Euclidean Distance):\n", numeric_similarity)


Nominal Similarity (Hamming Distance):
 [[1.  1.  0.  ... 0.  0.  0.5]
 [1.  1.  0.  ... 0.  0.  0.5]
 [0.  0.  1.  ... 1.  1.  0.5]
 ...
 [0.  0.  1.  ... 1.  1.  0.5]
 [0.  0.  1.  ... 1.  1.  0.5]
 [0.5 0.5 0.5 ... 0.5 0.5 1. ]]

Numeric Similarity (Euclidean Distance):
 [[ 1.          0.98349666  0.902498   ...  0.60124559 -0.73046414
   0.29058436]
 [ 0.98349666  1.          0.80967989 ...  0.73589476 -0.84197283
   0.11266955]
 [ 0.902498    0.80967989  1.         ...  0.1984707  -0.36509946
   0.67436114]
 ...
 [ 0.60124559  0.73589476  0.1984707  ...  1.         -0.98491014
  -0.5898716 ]
 [-0.73046414 -0.84197283 -0.36509946 ... -0.98491014  1.
   0.44121983]
 [ 0.29058436  0.11266955  0.67436114 ... -0.5898716   0.44121983
   1.        ]]


In [ ]:
merged_df.columns

Index(['AddressLine1', 'City', 'StateProvinceName', 'CountryRegionName',
       'PostalCode', 'BirthDate', 'Occupation', 'Gender', 'HomeOwnerFlag',
       'NumberCarsOwned', 'NumberChildrenAtHome', 'TotalChildren',
       'YearlyIncome', 'BikeBuyer', 'AvgMonthSpend'],
      dtype='object')